/* Supplementary practice bank grounded in Cannon, Perreault & McCarthy (18e).
   Extends the existing arrays without changing saved learner progress. */
(function(){
  'use strict';
  const D=window.SM; if(!D) return;
  const cards=[
    {sec:'s1',q:'Scenario · A platform removes wholesalers and claims it has eliminated distribution costs. What is the strongest response?',a:'Intermediaries can be removed, but the eight universal functions remain. Buying, selling, transport, storage, standardisation, financing, risk and information must be reassigned. Compare total-system cost and customer service before calling it disintermediation value. Source: Cannon et al., Ch. 1.'},
    {sec:'s1',q:'Scenario · A firm sells more to current customers using its existing product. Which opportunity direction is this?',a:'Market penetration: current product/current market. Contrast with market development (new market), product development (new product) and diversification (both new). Source: Cannon et al., Ch. 2.'},
    {sec:'s1',q:'Scenario · An opportunity passes customer-value and capability tests but its regulatory risk is unresolved. How should stoplight screening classify it?',a:'Yellow: do not approve or reject automatically. Specify the missing evidence, risk limit, experiment or condition that would turn it green or red. Source: Cannon et al., Ch. 3.'},
    {sec:'s1',q:'Scenario · A profitable company action transfers waste-disposal costs to a community. Which analytical level exposes the problem?',a:'Macro-marketing. Micro performance may look strong, but the wider marketing system must be evaluated for societal efficiency, fairness, sustainability and satisfaction. Source: Cannon et al., Chs. 1 and 19.'},
    {sec:'s1',q:'Scenario · Management introduces AI because competitors use it, without a defined customer problem. What is missing?',a:'Decision-led market orientation. Define the target need, value mechanism, evidence, capability and safeguard before choosing technology. Source: Study guide 3.2; Hooley Chs. 1-3; Cannon Ch. 3.'},
    {sec:'s1',q:'Scenario · A firm has an excellent capability that customers no longer value. Is it a strategic strength?',a:'No. Under RBV/VRIO, a capability must be valuable in the current or emerging market. Otherwise it may be a rigidity that accelerates strategic drift.'},

    {sec:'s2',q:'Scenario · A company donates to conservation while its core supply chain causes unreported environmental harm. Which Carroll responsibilities are in conflict?',a:'Philanthropic activity cannot compensate for unmet legal or ethical responsibility. Evaluate economic viability within legal, ethical and ecological constraints, then require operational correction and evidence. Source: Study guide 3.3; Hooley Ch. 17.'},
    {sec:'s2',q:'Scenario · Personalised pricing increases total welfare but systematically charges vulnerable customers more. Which ethical lenses reveal the problem?',a:'Justice/fairness exposes unequal burden; rights/duties question autonomy and non-discrimination; care highlights vulnerability. A utilitarian total alone is insufficient.'},
    {sec:'s2',q:'Scenario · A package says “planet friendly” without a baseline, scope or lifecycle evidence. Diagnose it.',a:'Likely greenwashing through a vague, unqualified claim. Require specific boundaries, method, comparative baseline, material outcome and assurance.'},
    {sec:'s2',q:'Scenario · A child can purchase repeatedly inside a game through one-click prompts. What safeguards are required?',a:'Age-appropriate design, meaningful parental control, spending limits, clear price disclosure, friction before repeat purchase and monitoring for harm. Vulnerability changes the ethical standard.'},
    {sec:'s2',q:'Scenario · A cause campaign generates excellent publicity but only a negligible donation. What should an exam answer evaluate?',a:'Company-cause fit, materiality, transparency of donation mechanics, stakeholder benefit, operational alignment and whether communication exceeds the real commitment.'},
    {sec:'s2',q:'Scenario · A practice is legal but relies on customers not understanding the terms. Is compliance sufficient?',a:'No. Law is a minimum and may lag practice. Apply transparency, rights, fairness, consequences, publicity and reversibility tests.'},

    {sec:'s3',q:'Scenario · Survey respondents prefer a brand, but shoppers repeatedly buy the available competitor. What explains the gap?',a:'Attitude is only one influence. Availability, habit, situational pressure, price, social context and perceived risk can interrupt intention. Source: Cannon et al., Ch. 5.'},
    {sec:'s3',q:'Scenario · A high-risk purchase leads the buyer to compare reviews, demonstrations and warranties. Which decision pattern applies?',a:'Extensive problem solving: high involvement and perceived risk produce wider search and evaluation. Marketing should provide credible proof, trial and risk reduction. Source: Cannon et al., Ch. 5.'},
    {sec:'s3',q:'Scenario · An engineer specifies a solution, procurement negotiates and the CFO authorises. Identify the buying-centre roles.',a:'Engineer: user/influencer; procurement: buyer and possible gatekeeper; CFO: decider. Map criteria and value proof separately for each. Source: Cannon et al., Ch. 6.'},
    {sec:'s3',q:'Scenario · An incumbent supplier wants a contract renewal to remain routine; a challenger reframes hidden downtime as a strategic risk. Which buy classes are involved?',a:'The incumbent seeks a straight rebuy; the challenger attempts to create a modified rebuy or new task by changing specifications and evaluation criteria.'},
    {sec:'s3',q:'Scenario · Two segments score similarly, but one ranking changes when a single weight moves slightly. What should management do?',a:'Conduct sensitivity analysis, identify the decisive assumption, collect better evidence and consider staged entry rather than claiming the score is objective.'},
    {sec:'s3',q:'Scenario · A CRM system targets high-revenue customers who generate low contribution after service costs. What metric corrects the error?',a:'Contribution-based CLV including acquisition, discounts, returns, service cost, churn probability and time value—not revenue alone.'},

    {sec:'s4',q:'Calculation · Price is R250 and variable cost is R150. What is unit contribution?',a:'R100 per unit: R250 − R150. Contribution is available to cover fixed cost and then profit. Source: Cannon et al., Ch. 18.'},
    {sec:'s4',q:'Calculation · Fixed cost is R600,000 and unit contribution is R120. What is break-even volume?',a:'5,000 units: R600,000 ÷ R120. This is a feasibility threshold, not proof that demand exists.'},
    {sec:'s4',q:'Calculation · An item costs R80 and sells for R100. Distinguish markup on cost from gross margin on selling price.',a:'Markup on cost = (100−80)÷80 = 25%. Margin on selling price = (100−80)÷100 = 20%. Always state the denominator.'},
    {sec:'s4',q:'Scenario · A salesperson wins volume by discounting, but margin and retention collapse. What caused the failure?',a:'Misaligned sales control. Compensation rewarded volume rather than customer fit, realised value, margin and retention. Redesign incentives and qualification. Source: Cannon et al., Ch. 14.'},
    {sec:'s4',q:'Scenario · A digital retailer adds stores, click-and-collect and app delivery but shows different prices and stock in each. Is this omnichannel?',a:'No. It is disconnected multichannel. Omnichannel requires integrated customer identity, inventory visibility, pricing rules, fulfilment and service standards.'},
    {sec:'s4',q:'Scenario · Faster transport reduces lead time but doubles freight cost and barely affects stockouts. What principle should guide the decision?',a:'Total-cost/service analysis. Compare inventory, transport, storage, processing, lost sales and segment service value rather than optimising speed alone. Source: Cannon et al., Ch. 11.'},
    {sec:'s4',q:'Scenario · A low-cost retailer gradually adds services, complexity and price, creating space for a new discounter. Which model?',a:'The wheel of retailing. Treat it as a recurring pattern, not an inevitability. Source: Cannon et al., Ch. 12.'},
    {sec:'s4',q:'Scenario · Customers know a brand but do not consider it because the association is outdated. What does this show?',a:'Awareness alone is insufficient. Diagnose salience in category-entry situations, associations, relevance, credibility and position; then change experience and proof, not only reach.'},
    {sec:'s4',q:'Scenario · A promotion creates a sales spike followed by lower full-price purchasing. What must evaluation include?',a:'Incremental volume, contribution, stockpiling, cannibalisation, post-promotion repeat and reference-price erosion—not campaign-period revenue alone.'},
    {sec:'s4',q:'Scenario · Reviews drive conversion after paid advertising created awareness. Which media types and attribution problem appear?',a:'Paid media created reach; earned media supplied reviews. Last-click attribution may overcredit the final touch. Test incrementality and complementary roles. Source: Cannon et al., Ch. 16.'},

    {sec:'s5',q:'Scenario · A segment strategy fails because sales incentives still reward legacy products. Is the failure strategic or implementation-related?',a:'Primarily implementation misalignment, though strategy feasibility should also be tested. Align incentives, account ownership, capability and measures using 7S.'},
    {sec:'s5',q:'Scenario · A dashboard shows all tasks completed but customer adoption is unchanged. What is wrong?',a:'Activity milestones have replaced benefits realisation. Add leading adoption measures and customer, process and financial outcomes tied to the strategy’s causal logic.'},
    {sec:'s5',q:'Scenario · An audit reports declining sales but never compares them with objectives or market change. Is it a strategic audit?',a:'No. An audit compares evidence with explicit expectations, examines environment, strategy, organisation, systems, productivity and functions, then prioritises corrective action.'},
    {sec:'s5',q:'Scenario · A new venture is uncertain but potentially transformative. What does real-options logic recommend?',a:'Stage investment through experiments that buy learning. Define evidence thresholds for scale, adaptation or abandonment rather than making one irreversible commitment.'},
    {sec:'s5',q:'Scenario · An Uber-style platform grows bookings while subsidies and service failures rise. What must be tested?',a:'Unit economics, liquidity quality, retention, multi-homing, stakeholder value distribution, safety, regulation and legitimacy—not adoption alone.'},
    {sec:'s5',q:'Scenario · Employees are trained on a new promise but policies prevent them from resolving customer problems. What is missing?',a:'Authority, process and system alignment. Internal marketing requires tools, workload, decision rights, incentives and leadership behaviour—not communication alone.'},
    {sec:'s1',q:'Scenario · A new-market proposal has high growth but requires capabilities the firm cannot organise. Which two tests fail?',a:'Resource/capability fit and organisation. External attractiveness alone cannot create advantage; develop, partner, stage or reject. Source: Hooley Chs. 2-3; Cannon Ch. 3.'},
    {sec:'s2',q:'Scenario · Management would not accept the same opaque practice if it were the customer. Which ethical test is this?',a:'Reversibility. It exposes self-serving standards by asking whether the decision remains acceptable when roles are exchanged.'},
    {sec:'s3',q:'Scenario · A survey instrument produces the same result repeatedly but measures satisfaction instead of loyalty. Diagnose it.',a:'It may be reliable but lacks construct validity for loyalty. Consistency does not prove the intended concept was measured.'},
    {sec:'s4',q:'Calculation · Price falls from R200 to R180 while volume rises from 1,000 to 1,080. Variable cost is R120. Did total contribution improve?',a:'Before: (200−120)×1,000 = R80,000. After: (180−120)×1,080 = R64,800. Volume rose, but contribution fell by R15,200.'},
    {sec:'s4',q:'Calculation · Fixed cost is R400,000, price R300 and variable cost R220. What happens to break-even if variable cost falls to R200?',a:'Original contribution R80, break-even 5,000 units. New contribution R100, break-even 4,000 units—a reduction of 1,000 units.'},
    {sec:'s5',q:'Scenario · A new strategy meets financial targets by excluding the target customers it was meant to serve. Can implementation be called successful?',a:'No. Performance must be judged against the complete strategic objective and stakeholder outcomes, not one financial measure.'}
  ];
  D.FLASHCARDS.push(...cards);

  const applied={
    s1:[{q:'A firm rates a new opportunity green on market growth but red on legal feasibility. What is the best decision?',options:['Average the colours and proceed','Ignore legal feasibility because growth is high','Reject or redesign until the decisive red constraint is resolved','Increase the advertising budget'],answer:2,explain:'Stoplight screening does not average away a decisive constraint. Red means stop or redesign; growth cannot legalise an infeasible strategy.'},{q:'Which action is market development?',options:['Sell more current service to current clients','Offer a new service to current clients','Take the current service into a new national segment','Enter a new market with a new service'],answer:2,explain:'Market development takes a current offer to a new market. Source: Cannon et al., Chapter 2.'}],
    s2:[{q:'A legal targeting practice uses opaque proxies that disadvantage a vulnerable group. Which response is strongest?',options:['Proceed because it is legal','Publish a CSR advert','Audit outcomes, remove unfair proxies and provide appeal','Collect more data without changing the model'],answer:2,explain:'Ethical governance extends beyond compliance and changes the design through fairness testing, limits, transparency and remedy.'},{q:'Which is the strongest evidence against a greenwashing allegation?',options:['A green colour palette','A celebrity endorsement','Specific lifecycle boundaries, baseline, outcome and independent assurance','A large media budget'],answer:2,explain:'Credibility comes from material, bounded and verifiable evidence rather than promotional intensity.'}],
    s3:[{q:'In a B2B new-task purchase, who typically controls the final authorisation?',options:['Only the end user','The decider, informed by the wider buying centre','The advertising agency','Any gatekeeper'],answer:1,explain:'The decider authorises, while users, influencers, buyers and gatekeepers shape requirements and access.'},{q:'A reliable attitude scale predicts purchase poorly because the product is unavailable. This is mainly a failure of…',options:['Reliability','Situational and behavioural diagnosis','Sample arithmetic','Brand awareness'],answer:1,explain:'A consistent attitude measure may still omit the situational constraint that prevents behaviour.'}],
    s4:[{q:'Fixed cost is R240,000, price R180 and variable cost R100. Break-even volume is…',options:['1,333 units','3,000 units','4,800 units','8,000 units'],answer:1,explain:'Contribution is R80; R240,000 ÷ R80 = 3,000 units.'},{q:'Which measure best evaluates a salesperson who sells a recurring complex solution?',options:['Calls made only','Gross bookings only','Realised customer value, contribution, retention and pipeline quality','Territory size'],answer:2,explain:'A balanced measure discourages mis-selling and connects sales effort to mutual long-term value.'},{q:'A company removes wholesalers but takes over warehousing, credit and risk. This demonstrates that…',options:['Channel functions disappeared','Disintermediation reallocates rather than eliminates functions','Direct channels are always cheaper','Wholesalers never add value'],answer:1,explain:'The functions and costs remain and must be compared at total-system level.'}],
    s5:[{q:'Which is a leading implementation indicator?',options:['Last year’s profit','Customer onboarding completion for the new offer','Historic market share','Prior-year revenue'],answer:1,explain:'Onboarding completion provides early evidence that the new strategy is being adopted.'},{q:'A pilot has explicit scale and stop thresholds. This is an example of…',options:['Strategic drift','Real-options logic','Mass marketing','Cost-plus pricing'],answer:1,explain:'A staged commitment buys learning while limiting downside and predetermining follow-on decisions.'}]
  };
  Object.keys(applied).forEach(sec=>D.QUIZ[sec].push(...applied[sec]));

  const modelSource={s1:'Study guide §3.2; Hooley Chapters 1-3; Cannon Chapters 1-3.',s2:'Study guide §3.3; Hooley Chapter 17; Cannon Chapters 1 and 19.',s3:'Study guide §3.4; Hooley Chapters 4 and 7-9; Cannon Chapters 4-7.',s4:'Study guide §3.5; Hooley Chapters 10-15; Cannon Chapters 8-18.',s5:'Study guide §3.6; Hooley Chapters 16 and 18; Cannon Chapters 2 and 19.'};
  D.EXAM.forEach(e=>{if(!e.source)e.source=modelSource[e.sec];});
  D.EXAM.push(
    {sec:'s4',tag:'CALC 1',marks:'12 marks',type:'Calculation',source:'Cannon Chapter 18, PDF pp. 587-614; study guide §3.5.3.',q:'A proposed service has fixed launch costs of R900,000, price of R750 and variable cost of R450 per subscription. Calculate break-even volume. If forecast demand is 2,800 subscriptions, assess the proposal.',model:'<span class="lbl">Calculation</span><p>Unit contribution = R750 − R450 = <strong>R300</strong>. Break-even volume = R900,000 ÷ R300 = <strong>3,000 subscriptions</strong>.</p><span class="lbl">Assessment</span><p>The base forecast is 200 subscriptions below break-even, producing a contribution shortfall of R60,000 before considering tax or financing. Do not reject mechanically: test price elasticity, variable-cost reduction, staged fixed cost, capacity and strategic/customer effects. Provide base, downside and upside scenarios.</p>'},
    {sec:'s4',tag:'CALC 2',marks:'15 marks',type:'Calculation',source:'Cannon Chapters 17-18; study guide §3.5.3.',q:'A retailer buys an item for R240 and sells it for R360. Calculate markup on cost and gross margin on selling price. Explain why confusing the two is dangerous.',model:'<span class="lbl">Calculation</span><p>Gross amount = R120. Markup on cost = 120 ÷ 240 = <strong>50%</strong>. Gross margin on selling price = 120 ÷ 360 = <strong>33.3%</strong>.</p><span class="lbl">Interpretation</span><p>The measures use different denominators. Confusion overstates realised margin and can corrupt budgets, channel negotiations and break-even estimates. Neither measure includes all fixed, service, return or acquisition costs.</p>'},
    {sec:'s3',tag:'CASE 1',marks:'20 marks',type:'Mini case',source:'Cannon Chapters 5-6, PDF pp. 159-220; study guide §3.4.',q:'A software supplier presents the same feature-heavy proposal to engineers, procurement and the CFO. Engineers approve technically, procurement rejects the terms and the CFO sees no strategic case. Analyse the failure and recommend a response.',model:'<span class="lbl">Diagnosis</span><p>The supplier treated an organisational buying centre as one customer. Engineers are users/influencers, procurement is buyer/gatekeeper and the CFO is decider. Their criteria differ.</p><span class="lbl">Response</span><ul class="note-list"><li>Map the buy class, roles, power and unresolved risk.</li><li>Translate technical features into workflow outcomes for users, total cost and terms for procurement, and strategic/financial value for the CFO.</li><li>Develop one coherent value case with role-specific evidence.</li><li>Plan implementation, adoption and realised-value review.</li></ul><span class="lbl">Judgement</span><p>More persuasion is not the answer; buying-centre alignment and credible value-in-use are.</p>'},
    {sec:'s4',tag:'CASE 2',marks:'20 marks',type:'Mini case',source:'Cannon Chapters 10-12, PDF pp. 321-412; study guide §3.5.3.',q:'An online retailer adds stores and click-and-collect. Customers encounter inconsistent prices, unavailable promised stock and difficult returns. Diagnose the channel problem and propose an omnichannel solution.',model:'<span class="lbl">Diagnosis</span><p>The firm has added channels without integrating service outputs, inventory, price rules, identity, fulfilment and reverse logistics. This is disconnected multichannel rather than omnichannel.</p><span class="lbl">Recommendation</span><ul class="note-list"><li>Define segment service outputs and each channel’s journey role.</li><li>Create real-time inventory visibility and common promise rules.</li><li>Clarify price architecture and ownership of the customer.</li><li>Design cross-channel returns and recovery.</li><li>Measure perfect orders, on-time/in-full, total cost-to-serve, returns and satisfaction.</li></ul>'},
    {sec:'s4',tag:'PLAN 1',marks:'30 marks',type:'Marketing-plan exercise',source:'Study guide §§3.5.3-3.5.4 and Appendix 3; Hooley Chapters 2 and 11; Cannon Chapters 2 and 19.',q:'Prepare an evidence-based one-year marketing plan for a South African SME launching a premium refillable household-cleaning service.',model:'<span class="lbl">Model plan</span><ul class="note-list"><li><strong>Situation:</strong> define category, PESTLE, customer jobs, alternatives, capability and baseline. Validate willingness to refill, convenience needs and credible sustainability evidence.</li><li><strong>Objectives:</strong> specify qualified trial, repeat rate, refill adoption, distribution/service level, contribution and awareness with baselines and dates.</li><li><strong>STP:</strong> prioritise an accessible segment that values convenience and verified waste reduction; position on effortless credible reuse, not vague “green”.</li><li><strong>Programme:</strong> durable product/return system; value-based subscription and trial; dense delivery/collection zones; evidence-led paid, owned and earned communication; trained service recovery.</li><li><strong>Economics:</strong> forecast acquisition, contribution, return logistics, capacity and break-even under three scenarios.</li><li><strong>Action/control:</strong> owners, 90-day pilot, consent and claim governance, weekly leading measures, quarterly review and scale/stop triggers.</li></ul><span class="lbl">What earns distinction</span><p>Coherence, explicit assumptions, source-grounded evidence, ethical safeguards and a justified trade-off—not the number of tactics.</p>'},
    {sec:'s3',tag:'PLAN 2',marks:'25 marks',type:'Marketing-plan exercise',source:'Study guide §3.4; Hooley Chapters 4 and 7-9; Cannon Chapters 4-7.',q:'Design the research and STP component of a marketing plan for a bank seeking to serve informal micro-enterprises.',model:'<span class="lbl">Model answer</span><p>Define the decision and market through financial jobs, not a demographic label. Use exploratory interviews/observation to understand cash-flow, trust, documentation and channel constraints; then quantify segment size, needs and response with a defensible sample. Develop needs/behaviour segments, test measurability, access, substantiality, differentiation and actionability, then compare attractiveness with bank capability. Address privacy, proxy discrimination and exclusion. Select a target conditionally and state the position, service design, pilot, adoption and customer-outcome measures.</p>'},
    {sec:'s5',tag:'ESSAY 1',marks:'30 marks',type:'Critical essay',source:'Study guide §3.6; Hooley Chapter 16; Cannon Chapters 2 and 19.',q:'“Most marketing strategies fail because of execution, not because of strategy.” Critically evaluate this statement.',model:'<span class="lbl">Thesis</span><p>The statement is too absolute. Underperformance can arise from flawed diagnosis/choice, poor translation, implementation misalignment or changed assumptions.</p><span class="lbl">Analysis</span><ul class="note-list"><li>Test strategy quality: market definition, evidence, STP, advantage, economics and ethics.</li><li>Use 7S to analyse structure, systems, skills, staff, style and shared values.</li><li>Explain internal marketing, decision rights, incentives, resources and capability.</li><li>Use leading indicators and the strategic audit to distinguish hypotheses.</li><li>Discuss emergent learning and environmental change.</li></ul><span class="lbl">Judgement</span><p>Execution and formulation are interdependent. A defensible conclusion diagnoses the dominant cause and recommends a learning system rather than using “execution” as a residual explanation.</p>'},
    {sec:'s2',tag:'ESSAY 2',marks:'30 marks',type:'Critical essay',source:'Study guide §3.3; Hooley Chapter 17; Cannon Chapters 1 and 19.',q:'“If a marketing practice is legal and profitable, management has fulfilled its responsibility.” Critically evaluate.',model:'<span class="lbl">Position</span><p>Reject the claim as insufficient. Law is a minimum and may lag technology; profit does not account for rights, fairness, vulnerability or externalised harm.</p><span class="lbl">Theory</span><p>Apply Carroll’s economic, legal, ethical and philanthropic responsibilities; shareholder and stakeholder views; utilitarian, rights, justice, virtue and care lenses.</p><span class="lbl">Application</span><p>Use a data, pricing or green-claim case to map stakeholders, power, consent, short/long-term consequences and alternatives. Recommend governance, evidence, limits, monitoring and remedy.</p><span class="lbl">Judgement</span><p>Economic viability is necessary but should be achieved within legal, ethical and ecological constraints that preserve legitimacy and stakeholder value.</p>'}
  );
})();
