(function(){
  'use strict';
  const ladders=[
    {
      id:'strategy',sec:'s1',tab:'3.2',title:'Market orientation and strategy',short:'Strategy',
      memory:'SENSE → SELECT → SERVE → STEER',deep:'deep-notes.html?note=market-orientation',
      source:'Study guide §3.2 · Hooley Chapters 1–3 · Cannon Chapters 1–3',
      steps:[
        {level:1,label:'Recall',prompt:'Define a market-driven strategy and explain why market orientation is more than “being customer friendly”.',hint:'Begin with the organisation’s outside-in starting point, then name intelligence generation, dissemination and coordinated response.',model:`<p>A <strong>market-driven strategy</strong> begins with markets, customers, competitors and environmental change rather than with the organisation’s existing products. Market orientation is the organisational capability that makes this possible: the firm generates market intelligence, shares it across functions and responds in a coordinated way.</p><p>It is therefore not a customer-service slogan. It affects resource allocation, capability development, target choice, value propositions and performance measurement. Customer preferences must also be interpreted alongside competitor behaviour, channel economics, ethics and the organisation’s ability to deliver defensible value.</p>`,rubric:['Accurate outside-in definition','Explains intelligence generation, sharing and response','Connects orientation to strategic choices and capabilities','Avoids equating it with customer service alone']},
        {level:2,label:'Distinguish',prompt:'Contrast production orientation with market orientation. Under what conditions might a production emphasis still be strategically rational?',hint:'Compare starting point, research, product range, pricing and risk. Then add a conditional qualification.',model:`<p>A production-oriented firm starts with what it can make efficiently, emphasising technical performance, scale, cost and distribution. A market-oriented firm starts with what selected customers value, using market intelligence to shape the offer, price and route to market.</p><p>Market orientation is usually more adaptive, but a production emphasis may be rational where demand substantially exceeds supply, customers value standardisation and low cost, technical reliability dominates choice, or process innovation creates a genuine cost advantage. The critical distinction is whether production efficiency serves a validated market opportunity or merely protects internal habits.</p>`,rubric:['Uses explicit comparison dimensions','Identifies benefits and risks of both orientations','Provides defensible boundary conditions','Ends with a conditional judgement']},
        {level:3,label:'Diagnose',prompt:'A successful appliance manufacturer keeps adding technical features while customer complaints, low-cost entrants and repair delays increase. Diagnose the strategic problem using market-orientation and strategic-drift concepts.',hint:'Separate symptoms from causes. Ask what intelligence is missing, where it fails to travel and why the response is inadequate.',model:`<p>The feature programme is a symptom of an <strong>inside-out orientation</strong>. The firm appears to privilege engineering output over evidence about total customer value, including affordability, reliability and after-sales service. Complaints and competitor moves may be visible but are not being converted into shared intelligence and coordinated action.</p><p>Strategic drift is emerging because environmental and customer change is moving faster than the strategy. Management should test intelligence-generation processes, cross-functional dissemination, incentives and service capabilities before assuming that more features will restore advantage.</p>`,rubric:['Diagnoses rather than merely describes','Uses market-orientation mechanisms','Explains strategic drift causally','Identifies evidence needed before recommending action']},
        {level:4,label:'Apply',prompt:'A regional mobile bank wants to enter a lower-income rural market. Build a concise SENSE–SELECT–SERVE–STEER plan.',hint:'Give one evidence-based decision under each heading and include an early learning measure.',model:`<p><strong>Sense:</strong> investigate cash-flow patterns, trust, handset access, connectivity, informal alternatives, regulation and agent economics. <strong>Select:</strong> prioritise a viable segment with a costly unmet job, such as secure low-value transfers, and define a trust-led value proposition.</p><p><strong>Serve:</strong> design low-data onboarding, transparent pricing, accessible cash-in/out partners and local-language support. <strong>Steer:</strong> pilot in a bounded region; track verified onboarding, active use, failed transactions, complaints, agent liquidity and contribution. Scale only if customer value, operational reliability and unit economics meet pre-agreed thresholds.</p>`,rubric:['Specific evidence under all four stages','Clear target and value proposition','Aligned offer, price and channel decisions','Measures learning, ethics and economics']},
        {level:5,label:'Evaluate',prompt:'“The customer is always right, so market-oriented firms should follow expressed customer preferences.” Critically evaluate this claim.',hint:'Consider latent needs, vulnerable customers, long-term value, innovation, competitor imitation and organisational capability.',model:`<p>The claim confuses market orientation with passive responsiveness. Expressed preferences are useful evidence, but customers may not articulate latent needs, understand technical trade-offs or anticipate future possibilities. Following every request can fragment the offer, destroy economics and produce undifferentiated imitation.</p><p>A mature market orientation triangulates customer evidence with observation, experimentation, competitor intelligence, ethics and capability. It distinguishes valuable demand from short-term preference and protects vulnerable stakeholders. The firm should therefore learn from customers without surrendering strategic judgement; the appropriate response depends on evidence quality, segment value, feasibility and long-term consequences.</p>`,rubric:['Challenges the premise rather than accepting it','Uses competing arguments and boundary conditions','Includes ethics and capability constraints','Provides a justified, conditional conclusion']}
      ]
    },
    {
      id:'ethics',sec:'s2',tab:'3.3',title:'Ethics, CSR and defensible value',short:'Ethics',
      memory:'CARROLL + RIGHT',deep:'deep-notes.html?note=ethics-csr',
      source:'Study guide §3.3 · Hooley Chapter 17 · Cannon Chapters 1 and 19',
      steps:[
        {level:1,label:'Recall',prompt:'Explain Carroll’s four responsibilities and the purpose of the RIGHT decision test.',hint:'Economic, legal, ethical and philanthropic responsibilities operate together. RIGHT tests the decision from five angles.',model:`<p>Carroll’s framework presents <strong>economic</strong> responsibility as the viable foundation, followed by <strong>legal</strong>, <strong>ethical</strong> and <strong>philanthropic</strong> expectations. They are simultaneous responsibilities: voluntary giving cannot compensate for unlawful or harmful core activity.</p><p>The site’s RIGHT mnemonic broadens ethical analysis: <strong>R</strong>ights and duties, <strong>I</strong>mpacts and consequences, <strong>G</strong>roups and fairness, <strong>H</strong>onesty and publicity, and <strong>T</strong>racking, remedy and learning. It prevents an answer from treating legality or philanthropy as sufficient.</p>`,rubric:['Correct four-part framework','Explains simultaneity','Accurately expands RIGHT','Explains why both tools are needed']},
        {level:2,label:'Distinguish',prompt:'Distinguish legal compliance from ethical marketing. Why can a legally permitted campaign still be indefensible?',hint:'Law sets a floor. Consider information asymmetry, vulnerability, fairness and harms not yet regulated.',model:`<p>Legal compliance asks whether conduct meets binding rules; ethical marketing asks whether the decision is fair, honest, rights-respecting and defensible to affected stakeholders. Regulation often lags technology and cannot specify every use of data, targeting or persuasion.</p><p>A lawful campaign may exploit vulnerability, conceal material conditions, use discriminatory proxies or externalise harm. Ethical judgement therefore goes beyond the legal floor by examining foreseeable consequences, power asymmetries, informed consent, alternatives, safeguards and remedy.</p>`,rubric:['States law as necessary but not sufficient','Names concrete ethical mechanisms','Recognises regulation can lag practice','Uses stakeholder consequences, not personal opinion alone']},
        {level:3,label:'Diagnose',prompt:'A fashion brand advertises a collection as “planet positive” because its packaging is recyclable, while giving no evidence about production emissions. Diagnose the ethical failures.',hint:'Apply the green-claims domain and at least three RIGHT tests.',model:`<p>The claim risks greenwashing because its scope is narrow while its wording implies a net lifecycle benefit. Under <strong>H</strong>, the communication may fail honesty and publicity; under <strong>I</strong>, it ignores material production impacts; under <strong>G</strong>, it shifts information risk to customers and disadvantages competitors making substantiated claims.</p><p>The company should define scope and baseline, substantiate material lifecycle effects, qualify the wording, obtain independent assurance where appropriate and create a correction mechanism. Recyclable packaging may be positive, but it cannot justify the broader claim.</p>`,rubric:['Identifies scope mismatch and material omission','Applies named RIGHT dimensions','Separates evidence from rhetoric','Recommends proportional safeguards and remedy']},
        {level:4,label:'Apply',prompt:'An insurer plans AI-personalised prices using behavioural and location data. Apply RIGHT and recommend governance safeguards.',hint:'Address purpose, consent, proxy discrimination, explanation, appeal, monitoring and commercial viability.',model:`<p><strong>Rights:</strong> establish a lawful, understandable purpose and meaningful data controls. <strong>Impact:</strong> test affordability, exclusion and behavioural effects. <strong>Groups:</strong> audit variables and outcomes for discriminatory proxies. <strong>Honesty:</strong> explain material pricing factors without deceptive opacity. <strong>Track:</strong> monitor outcomes, enable appeal, correct errors and suspend harmful models.</p><p>A controlled pilot may be defensible if data minimisation, fairness testing, human review, appeal and board accountability are built in. Commercial benefit alone is insufficient; the recommendation depends on demonstrated predictive value without disproportionate harm.</p>`,rubric:['Applies every RIGHT element','Identifies vulnerable groups and proxy risk','Includes monitoring, appeal and remedy','Makes a conditional business recommendation']},
        {level:5,label:'Evaluate',prompt:'A highly profitable cause-marketing campaign donates only 1% of sales to the cause. Critically evaluate whether the campaign is responsible.',hint:'Do not decide from the percentage alone. Examine fit, transparency, incremental benefit, stakeholder expectations and core-business conduct.',model:`<p>The donation percentage is relevant but not decisive. Evaluation should consider the absolute and incremental benefit, fit between brand and cause, clarity of the mechanism, administrative costs, stakeholder expectations and whether promotional claims exaggerate impact.</p><p>Carroll’s framework also requires scrutiny of the core business: philanthropy cannot offset harmful labour, environmental or customer practices. The campaign is defensible only if the contribution is material relative to the claim, communication is transparent, operational conduct is aligned and affected stakeholders receive genuine value. Otherwise it becomes reputational appropriation rather than responsibility.</p>`,rubric:['Uses criteria rather than moral assertion','Evaluates both campaign and core business','Considers alternatives and materiality','Reaches a conditional, accountable judgement']}
      ]
    },
    {
      id:'markets',sec:'s3',tab:'3.4',title:'Markets, segmentation and target choice',short:'Markets & STP',
      memory:'DEFINE → DIVIDE → VALIDATE → EVALUATE → SELECT → POSITION',deep:'deep-notes.html?note=segmentation-targeting',
      source:'Study guide §3.4 · Hooley Chapters 4 and 7–9 · Cannon Chapters 4–7',
      steps:[
        {level:1,label:'Recall',prompt:'Define segmentation, targeting and positioning and explain their logical sequence.',hint:'Segmentation creates meaningful groups; targeting chooses; positioning establishes a distinctive meaning for the chosen target.',model:`<p><strong>Segmentation</strong> divides a heterogeneous market into groups with meaningfully different needs, behaviour or response. <strong>Targeting</strong> evaluates those groups and selects where the organisation will compete. <strong>Positioning</strong> defines the distinctive, credible meaning the offer should occupy for the selected target relative to alternatives.</p><p>The sequence matters: without valid segments, target choice is arbitrary; without target choice, positioning becomes generic; without a credible position, the marketing mix cannot be coherently designed.</p>`,rubric:['Accurate definitions','Explains the sequence causally','Recognises response differences, not labels alone','Connects positioning to alternatives and execution']},
        {level:2,label:'Distinguish',prompt:'Distinguish a demographic category from an actionable segment. Give an example of a misleading segmentation label.',hint:'Test measurability, accessibility, distinct response, size and strategic usefulness.',model:`<p>A demographic category describes people who share an observable characteristic; an actionable segment groups customers whose needs or responses differ in a way that changes strategy. “People aged 18–35” is not automatically a segment because age alone may not predict the job, benefits sought, channel or price response.</p><p>For example, “young professionals” can conceal commuters seeking convenience, status seekers and budget-constrained first-job consumers. A valid scheme must be measurable, reachable, sufficiently substantial, internally coherent, distinct in response and usable for positioning and the marketing programme.</p>`,rubric:['Explains why description is not segmentation','Uses actionability criteria','Provides a credible counterexample','Shows how strategy would change']},
        {level:3,label:'Diagnose',prompt:'A meal-delivery firm targets “all urban adults” but acquisition costs rise and repeat orders fall. Diagnose the likely STP failures and specify the evidence required.',hint:'Consider segment definition, need state, occasion, unit economics, reachability and position.',model:`<p>The target is too broad to support a specific value proposition or efficient acquisition. Different urban adults vary by occasion, household structure, dietary need, convenience threshold and willingness to pay. Falling repeat use suggests the acquired customers may not experience sufficient ongoing value.</p><p>The firm should analyse behavioural cohorts, occasions, contribution after delivery cost, retention, channel response and unmet jobs. It must then compare segment attractiveness with organisational fit and test distinct positions. The evidence should establish whether the problem is target quality, promise relevance, service delivery or economics.</p>`,rubric:['Diagnoses multiple possible mechanisms','Requests behavioural and economic evidence','Separates acquisition from retention','Avoids recommending a segment without validation']},
        {level:4,label:'Apply',prompt:'A small university offers a new online MBA. Evaluate three plausible segments and recommend a targeting approach.',hint:'Use attractiveness × competitive fit. Include reachability, profitability, capability and risk.',model:`<p>Plausible segments include career accelerators seeking credentials, experienced managers needing flexible applied learning, and entrepreneurs seeking decision tools. Each should be evaluated for size and growth, willingness to pay, acquisition cost, retention risk, competitive intensity and institutional fit.</p><p>A selective strategy focused on experienced working managers may be strongest if the university can prove flexible support, credible faculty and workplace application. Career accelerators could be secondary if placement evidence is strong. The recommendation should be tested through differentiated messages, enquiry-to-enrolment conversion, engagement, completion and contribution—not enrolment volume alone.</p>`,rubric:['Defines response-based segments','Uses attractiveness and fit criteria','Chooses a defensible targeting pattern','Specifies evidence and metrics']},
        {level:5,label:'Evaluate',prompt:'“The largest and fastest-growing segment is always the best target.” Critically evaluate.',hint:'Separate market attractiveness from competitive position and cost-to-serve.',model:`<p>Size and growth can increase revenue potential, but they also attract competitors, increase acquisition costs and expose the firm to powerful buyers. A large segment may require capabilities, channels or investment the organisation lacks, while a smaller segment can offer stronger fit, loyalty and contribution.</p><p>Target choice should combine segment attractiveness with competitive position, access, economics, strategic coherence, ethics and risk. The best target is therefore the segment where the organisation can create and appropriate superior value under realistic conditions—not automatically the largest one.</p>`,rubric:['Challenges single-criterion choice','Integrates attractiveness and fit','Includes competition and unit economics','Reaches a conditional recommendation']}
      ]
    },
    {
      id:'mix',sec:'s4',tab:'3.5',title:'Positioning and the connected marketing mix',short:'Position & mix',
      memory:'TARGET → FRAME → DIFFERENCE → PROOF',deep:'deep-notes.html?note=positioning-advantage',
      source:'Study guide §3.5 · Hooley Chapters 10–15 · Cannon Chapters 8–18',
      steps:[
        {level:1,label:'Recall',prompt:'Explain the T-F-D-P positioning structure and why the 4Ps must be treated as an interconnected system.',hint:'Target, frame of reference, difference and proof. Each marketing activity must make the same promise credible.',model:`<p>A positioning statement identifies the <strong>target</strong>, the relevant <strong>frame of reference</strong>, the valued <strong>difference</strong> and the <strong>proof</strong> or reason to believe. It is a strategic hypothesis about why a chosen customer should prefer the offer.</p><p>Product, price, place and promotion are interdependent evidence for that hypothesis. Product must deliver the benefit, price must fit its value meaning, distribution must make the experience obtainable and communication must make it noticeable and credible. A contradiction in one element can weaken the whole position.</p>`,rubric:['Accurately expands T-F-D-P','Defines positioning relative to alternatives','Explains the role of each P','Shows why coherence matters']},
        {level:2,label:'Distinguish',prompt:'Distinguish a product attribute, a customer benefit and a competitive position using one example.',hint:'An attribute is what the offer has; a benefit is what it does for the customer; a position is the relative meaning in a chosen frame.',model:`<p>For an electric vehicle, long battery range is an <strong>attribute</strong>. Reduced charging anxiety on long trips is a customer <strong>benefit</strong>. “The dependable long-distance electric vehicle for regional business travellers” is a <strong>position</strong> because it specifies a target, frame and distinctive meaning relative to alternatives.</p><p>Attributes become strategically valuable only when customers value the resulting benefit, competitors cannot easily neutralise it and the organisation can consistently prove and deliver it.</p>`,rubric:['Makes all three distinctions clear','Uses one coherent example','Includes target and competitive frame','Links proof to defensibility']},
        {level:3,label:'Diagnose',prompt:'A premium skincare brand sells through discount outlets, runs constant price promotions and uses clinical advertising without evidence. Diagnose the positioning problem.',hint:'Test each marketing-mix element against the intended premium promise.',model:`<p>The intended premium position is contradicted by price and place. Constant discounting trains customers to question the reference price, while uncontrolled discount distribution weakens exclusivity and service expectations. Unsupported clinical advertising also undermines proof and creates ethical risk.</p><p>Management should clarify the target and frame, verify which difference customers value, develop substantiated proof, redesign channel roles and establish price architecture. The answer is not necessarily to remove every discount outlet; the mix should be changed according to channel economics, customer access and the credibility of the chosen position.</p>`,rubric:['Identifies contradictions across several Ps','Connects inconsistency to customer meaning','Includes evidence and ethical risk','Avoids an unconditional cosmetic fix']},
        {level:4,label:'Apply',prompt:'Design a connected marketing mix for a refillable household-cleaning brand aimed at cost-conscious families.',hint:'Make every P support a position combining affordability, effectiveness and reduced waste.',model:`<p><strong>Product:</strong> durable starter bottle, concentrated refills, clear dosage and independently tested cleaning performance. <strong>Price:</strong> an accessible starter price with visible lower cost per use. <strong>Place:</strong> supermarket refill aisles plus convenient subscription replenishment. <strong>Promotion:</strong> demonstrate cleaning performance, cost per use and verified packaging reduction.</p><p>The proof system should use transparent baselines and lifecycle boundaries. Measures should include trial, refill rate, repeat purchase, cost per use perception, contribution, packaging reduction and complaints. If refill friction depresses repeat use, convenience—not communication—must be redesigned.</p>`,rubric:['Every P supports one position','Includes credible proof','Balances customer value and economics','Uses outcome and learning measures']},
        {level:5,label:'Evaluate',prompt:'A price reduction is forecast to increase unit sales by 25%. Should the firm proceed? Give a master’s-level evaluation.',hint:'Volume is not value. Examine contribution, elasticity assumptions, reference price, capacity, channel reaction and strategic meaning.',model:`<p>The forecast is insufficient without contribution analysis. Management should compare the lower contribution per unit with incremental volume, acquisition or promotional cost, capacity constraints and likely competitor response. The elasticity estimate should be tested by segment and time horizon.</p><p>Strategically, a discount may damage premium meaning, reset reference prices or trigger channel conflict. A bounded experiment may be appropriate where the target is price sensitive and capacity exists, but the decision should use contribution, repeat behaviour and brand effects—not unit volume alone.</p>`,rubric:['Calculates or discusses contribution logic','Challenges forecast assumptions','Includes positioning and channel effects','Recommends a testable conditional decision']}
      ]
    },
    {
      id:'implementation',sec:'s5',tab:'3.6',title:'Implementation, audit and adaptation',short:'Implementation',
      memory:'OWN → ALIGN → ACT → MEASURE → ADAPT',deep:'deep-notes.html?note=implementation-audit',
      source:'Study guide §3.6 · Hooley Chapters 16 and 18 · Cannon Chapters 2 and 19',
      steps:[
        {level:1,label:'Recall',prompt:'Explain the OAAMA implementation loop and the role of a marketing audit.',hint:'Ownership, alignment, action, measurement and adaptation. The audit tests evidence against objectives and assumptions.',model:`<p><strong>Own</strong> assigns accountability; <strong>Align</strong> fits structure, people, resources, systems and incentives; <strong>Act</strong> converts strategy into sequenced commitments; <strong>Measure</strong> tracks leading and lagging evidence; <strong>Adapt</strong> changes action or assumptions as learning emerges.</p><p>A marketing audit is a systematic examination of environment, objectives, strategy, organisation, systems, productivity and functions. It is not merely a sales report: it compares evidence with expectations, diagnoses causes and prioritises corrective action.</p>`,rubric:['Accurately explains all OAAMA stages','Defines audit as systematic and evidence-based','Includes objectives and assumptions','Connects diagnosis to corrective action']},
        {level:2,label:'Distinguish',prompt:'Distinguish poor strategy, poor implementation and changed assumptions. Why does the distinction matter?',hint:'The same weak result can have different causes and therefore different remedies.',model:`<p><strong>Poor strategy</strong> means the target, value proposition or economic logic was flawed. <strong>Poor implementation</strong> means a sound strategic choice was not delivered because ownership, capabilities, resources or coordination failed. <strong>Changed assumptions</strong> means the original logic was reasonable but the environment shifted.</p><p>The distinction matters because remedies differ: intensifying execution will not repair a bad target, while abandoning a sound strategy may reward avoidable execution failure. Management needs evidence about customer response, delivery quality, competitive change and causal assumptions before acting.</p>`,rubric:['Defines all three causes','Explains why outcomes alone cannot diagnose','Matches causes to different remedies','Requests discriminating evidence']},
        {level:3,label:'Diagnose',prompt:'A new loyalty programme has low enrolment. Marketing blames store staff; store staff blame an unattractive reward. Diagnose what should be investigated before deciding.',hint:'Use strategy, implementation and assumption categories. Include leading indicators.',model:`<p>Strategic evidence should test whether the target values the reward, whether switching behaviour is realistic and whether the economics are viable. Implementation evidence should test staff understanding, invitation rates, enrolment friction, system reliability and incentive alignment. Assumptions about privacy concern, competitor offers or channel behaviour may also have changed.</p><p>Leading indicators such as eligible customers invited, completion by step, activation and first reward use can locate failure before relying on aggregate enrolment. The response should follow the diagnosed constraint rather than departmental attribution.</p>`,rubric:['Investigates all three causal categories','Uses leading process indicators','Avoids blame-based diagnosis','Links evidence to possible remedies']},
        {level:4,label:'Apply',prompt:'Build a 90-day implementation plan for introducing a B2B key-account programme.',hint:'Specify owner, alignment, actions, measures, review points and scale/stop thresholds.',model:`<p><strong>Own:</strong> appoint an executive sponsor and accountable programme lead. <strong>Align:</strong> define account criteria, roles, CRM data, service capacity, incentives and finance rules. <strong>Act:</strong> pilot with a small, representative account group; create account plans and cross-functional reviews.</p><p><strong>Measure:</strong> track stakeholder coverage, opportunity progression, service performance, margin and retention—not revenue alone. <strong>Adapt:</strong> review at 30, 60 and 90 days. Scale if relationship depth, contribution and delivery quality improve; redesign or stop if administrative cost rises without customer or economic value.</p>`,rubric:['Names accountable ownership','Aligns structure, systems and incentives','Uses leading and lagging measures','Includes explicit learning and thresholds']},
        {level:5,label:'Evaluate',prompt:'“Once a strategy is approved, disciplined managers should resist adaptation.” Critically evaluate.',hint:'Balance commitment and consistency against learning, drift and opportunistic change.',model:`<p>Implementation requires commitment because constant changes can confuse employees, fragment resources and prevent valid evaluation. However, rigid persistence is dangerous when assumptions fail, competitor behaviour changes or leading evidence reveals customer harm or weak economics.</p><p>Disciplined adaptation is not reactive improvisation. It preserves the strategic objective while testing mechanisms, uses pre-agreed thresholds, distinguishes noise from meaningful change and records learning. Managers should therefore resist unsupported churn but adapt when credible evidence challenges the causal logic or operating conditions.</p>`,rubric:['Presents arguments for persistence and adaptation','Defines disciplined learning mechanisms','Uses thresholds and assumptions','Reaches a balanced conditional judgement']}
      ]
    },
    {
      id:'exam',sec:'all',tab:'Exam',title:'Exam analysis and judgement',short:'Exam toolkit',
      memory:'DIAGNOSE → REASON → EVIDENCE → APPLY → MEASURE',deep:'deep-notes.html',
      source:'Study guide learning outcomes · Existing exam bank and model-answer standards',
      steps:[
        {level:1,label:'Recall',prompt:'What distinguishes description, analysis and evaluation in a master’s-level marketing answer?',hint:'Description says what; analysis explains relationships and causes; evaluation judges using criteria and alternatives.',model:`<p><strong>Description</strong> accurately states concepts or case facts. <strong>Analysis</strong> explains how and why variables relate, using theory to identify mechanisms and consequences. <strong>Evaluation</strong> applies explicit criteria, considers strengths, limits and alternatives, and reaches a justified conditional judgement.</p><p>A strong answer integrates all three: accurate theory, causal application to case evidence, and a recommendation whose validity depends on stated assumptions and trade-offs.</p>`,rubric:['Correctly differentiates the three levels','Includes causal mechanism','Uses criteria and alternatives','Connects judgement to conditions']},
        {level:2,label:'Distinguish',prompt:'Rewrite this descriptive statement as analysis: “The company should segment the market and use social media.”',hint:'Name evidence, mechanism, target choice, channel role and outcome.',model:`<p>Transaction and research data should first test whether customer groups differ materially in need, response and profitability. If a reachable segment values rapid, peer-supported product discovery, selected social platforms could reduce information friction and provide credible demonstration.</p><p>However, channel choice should follow the segment and buying journey rather than fashion. Management should compare acquisition quality, conversion, retention and contribution with alternatives, while controlling privacy and reputational risk.</p>`,rubric:['Replaces generic prescription with evidence','Explains a causal mechanism','Connects channel to segment and journey','Adds measures, alternatives and risk']},
        {level:3,label:'Calculate',prompt:'A campaign has fixed costs of R600,000. Selling price is R320 and variable cost is R200 per unit. Calculate break-even volume and interpret the result.',hint:'Contribution per unit = price − variable cost. Break-even units = fixed costs ÷ contribution.',model:`<p><strong>Contribution per unit:</strong> R320 − R200 = <strong>R120</strong>.</p><p><strong>Break-even volume:</strong> R600,000 ÷ R120 = <strong>5,000 units</strong>.</p><p>The result is a threshold, not a recommendation. Management must assess whether demand can exceed 5,000 units within the relevant period, whether capacity and channel support exist, whether the price is sustainable and whether fixed and variable cost assumptions are complete.</p>`,rubric:['Writes the formulas','Substitutes correctly with units','Obtains 5,000 units','Interprets demand, capacity and assumption risk']},
        {level:4,label:'Apply',prompt:'Plan a 20-mark answer: “Recommend how a struggling regional retailer should respond to a digital entrant.”',hint:'Use an answer spine: diagnose → theory → alternatives → recommendation → implementation → measures.',model:`<p><strong>Diagnose:</strong> establish whether decline reflects target erosion, value disadvantage, channel friction, cost structure or execution. <strong>Theory:</strong> use market orientation, customer journey, positioning and capability analysis. <strong>Alternatives:</strong> compare imitation, focused differentiation, partnership and omnichannel redesign.</p><p><strong>Recommendation:</strong> select a target-specific response based on evidence rather than “go digital”. <strong>Implementation:</strong> define owner, capabilities, pilot and safeguards. <strong>Measures:</strong> track adoption, conversion, service quality, retention and contribution. Include a counterargument and conditions under which the preferred option should be changed.</p>`,rubric:['Provides a logical answer architecture','Uses several relevant theories purposefully','Compares alternatives','Includes implementation, metrics and conditions']},
        {level:5,label:'Evaluate',prompt:'Produce a conditional recommendation for a firm considering aggressive personalised pricing. Include a counterargument and safeguards.',hint:'Your conclusion should state when the strategy is acceptable, when it is not and how management will know.',model:`<p>Personalised pricing may improve conversion and capacity utilisation where price sensitivity genuinely differs, customers retain meaningful choice and segmentation variables are relevant rather than exploitative. The counterargument is that opaque differentials can damage trust, discriminate through proxies and transfer value from vulnerable customers.</p><p>A limited pilot is defensible only with purpose limitation, fairness testing, price boundaries, clear communication where material, human appeal and outcome monitoring. Management should stop or redesign if protected or vulnerable groups face systematic disadvantage, complaints rise, trust falls or incremental contribution depends on deception.</p>`,rubric:['States a defensible strategic benefit','Develops a serious counterargument','Specifies operational safeguards','Uses explicit scale, redesign or stop conditions']}
      ]
    }
  ];
  if(typeof window!=='undefined') window.SM_PRACTICE={ladders:ladders};
})();
